import Head from "next/head";
import { Fragment } from "react";

export default function Login() {
    return (
        <Fragment>
            <Head>
                <title>Authorization | Login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>Login page</h1>
        </Fragment>
    );
}
